---
platform: linux
image: docker:///cloudfoundry/forge-ci
inputs:
- name: forge-ci
- name: deploy-vagrant-aws
run:
  path: forge-ci/tasks/cluster-test-vagrant-aws-s3/run.sh
params:
  AWS_ACCESS_KEY_ID: some-access-key-id
  AWS_SECRET_ACCESS_KEY: some-secret-access-key
  AWS_REGION: some-region
  S3_BUCKET_NAME: some-bucket-name
