---
platform: linux
image: docker:///cloudfoundry/forge-ci
inputs:
- name: forge-ci
run:
  path: forge-ci/tasks/deploy-vsphere-bosh/run.sh
params:
  VCENTER_ADDRESS: some-vcenter-address
  VCENTER_USERNAME: some-vcenter-username
  VCENTER_PASSWORD: some-vcenter-password
