---
platform: linux
image: docker:///micropcf/ci
inputs:
- name: micropcf-ci
- name: vsphere-bosh-state
run:
  path: micropcf-ci/tasks/deploy-vsphere-bosh/run.sh
params:
  VCENTER_ADDRESS: some-vcenter-address
  VCENTER_USERNAME: some-vcenter-username
  VCENTER_PASSWORD: some-vcenter-password
