---
platform: linux
image: docker:///cloudfoundry/forge-ci
inputs:
- name: forge-ci
run:
  path: forge-ci/tasks/generate-vsphere-worker-manifest/run.sh
params:
  VSPHERE_WORKER_PRIVATE_KEY: some-vsphere-worker-private-key
  CONCOURSE_TSA_PUBLIC_KEY: some-concourse-tsa-public-key
  BOSH_TARGET: some-bosh-target
  BOSH_PASSWORD: some-bosh-password
