---
platform: linux
image: docker:///cloudfoundry/forge-ci
inputs:
- name: forge-ci
- name: forge-bundle-ci
run:
  path: forge-ci/tasks/deploy-vagrant-aws/run.sh
params:
  AWS_ACCESS_KEY_ID: some-access-key-id
  AWS_SECRET_ACCESS_KEY: some-secret-access-key
  AWS_SSH_PRIVATE_KEY: some-ssh-private-key
  AWS_SSH_PRIVATE_KEY_NAME: some-ssh-private-key-name
  IGNORE_VERSION_MISMATCH: false
