---
platform: linux
image: docker:///micropcf/ci
inputs:
- name: micropcf-ci
- name: micropcf
- name: deploy
run:
  path: micropcf-ci/tasks/dats/run.sh
params:
  AWS_ACCESS_KEY_ID: some-access-key-id
  AWS_SECRET_ACCESS_KEY: some-secret-access-key
  AWS_SSH_PRIVATE_KEY: some-ssh-private-key
  AWS_SSH_PRIVATE_KEY_NAME: some-ssh-private-key-name
