---
platform: linux
image: docker:///cloudfoundry/forge-ci
inputs:
- name: forge-ci
run:
  path: forge-ci/tasks/apply-cloudformation/run.sh
params:
  CLOUDFORMATION_STACK_NAME: some-stack-name
  CERTIFICATE_NAME: some-certificate-name
  AWS_DEFAULT_REGION: some-aws-region
  AWS_ACCESS_KEY_ID: some-aws-access-key-id
  AWS_SECRET_ACCESS_KEY: some-aws-secret-access-key
