---
platform: linux
image: docker:///cloudfoundry/forge-ci
inputs:
- name: forge-ci
- name: forge
- name: forge-tgz
- name: vagrant-box-version
- name: terraform-ami-metadata
run:
  path: forge-ci/tasks/build-bundle/run.sh
