---
platform: linux
image: docker:///cloudfoundry/cf-local-ci
inputs:
- name: cf-local-ci
- name: cf-local-release
- name: cf-local-tgz
- name: vagrant-box-version
- name: terraform-ami-metadata
run:
  path: cf-local-ci/tasks/build-bundle/run.sh
