---
platform: linux
image: docker:///cloudfoundry/micropcf-ci
inputs:
- name: micropcf-ci
- name: micropcf
- name: micropcf-tgz
- name: vagrant-box-version
- name: terraform-ami-metadata
run:
  path: micropcf-ci/tasks/build-bundle/run.sh
