---
platform: linux
image: docker:///cloudfoundry/cf-local-ci
inputs:
- name: cf-local-ci
run:
  path: cf-local-ci/tasks/deploy-bosh/run.sh
params:
  CLOUDFORMATION_STACK_NAME: some-stack-name
  AWS_DEFAULT_REGION: some-aws-region
  AWS_ACCESS_KEY_ID: some-aws-access-key-id
  AWS_SECRET_ACCESS_KEY: some-aws-secret-access-key
  BOSH_PRIVATE_KEY: some-bosh-private-key
