---
platform: linux
image: docker:///cloudfoundry/cf-local-ci
inputs:
- name: cf-local-ci
- name: cf-local-release
- name: cf-local-tgz-version
run:
  path: cf-local-ci/tasks/compile-cf-local-tgz/run.sh

