---
platform: linux
image: docker:///micropcf/ci
inputs:
- name: micropcf-ci
- name: micropcf-website
run:
  path: micropcf-ci/tasks/deploy-micropcf-website/run.sh
params:
  GITHUB_SSH_KEY: some-ssh-key
