---
platform: linux
image: docker:///cloudfoundry/cf-local-ci
inputs:
- name: cf-local-ci
- name: cf-local-bundle-ci
run:
  path: cf-local-ci/tasks/deploy-terraform-aws/run.sh
params:
  AWS_ACCESS_KEY_ID: some-access-key-id
  AWS_SECRET_ACCESS_KEY: some-secret-access-key
  AWS_SSH_PRIVATE_KEY: some-ssh-private-key
  AWS_SSH_PRIVATE_KEY_NAME: some-ssh-private-key-name
