---
platform: linux
image: docker:///cloudfoundry/cf-local-ci
inputs:
- name: cf-local-ci
- name: cf-local-release
run:
  path: cf-local-ci/tasks/build-release/run.sh
params:
  AWS_ACCESS_KEY_ID: some-aws-access-key-id
  AWS_SECRET_ACCESS_KEY: some-aws-secret-access-key
  S3_BUCKET_NAME: some-s3-bucket-name
