---
platform: linux
image: docker:///micropcf/ci
inputs:
- name: micropcf-ci
run:
  path: micropcf-ci/tasks/generate-vagrantfile-listing/run.sh
params:
  AWS_ACCESS_KEY_ID: some-access-key-id
  AWS_SECRET_ACCESS_KEY: some-secret-access-key
